CREATE DATABASE DETAILS;
USE DETAILS;
CREATE TABLE EMPLOYEE_DETAILS(id int,id_num bigint);
CREATE TABLE AIRPORT_DETAILS(id int, id_num bigint);
alter table EMPLOYEE_DETAILS add column (emp_salary bigint,emp_loc varchar (20), emp_age int,emp_mob_num bigint,emp_aadhar_num bigint);
alter table AIRPORT_DETAILS add column (p_num bigint, seat_num bigint, g_num bigint, a_num bigint,location varchar(20));
alter table EMPLOYEE_DETAILS drop column emp_age ;
alter table EMPLOYEE_DETAILS drop column emp_loc ;
alter table AIRPORT_DETAILS drop column g_num ;
alter table AIRPORT_DETAILS drop column p_num ;
alter table EMPLOYEE_DETAILS rename column emp_mob_num to mob_num;
alter table EMPLOYEE_DETAILS rename column emp_aadhar_num to a_num;
alter table EMPLOYEE_DETAILS rename column a_num to aadhar_num;
alter table EMPLOYEE_DETAILS rename column id_num to emp_num;
alter table EMPLOYEE_DETAILS rename column emp_salary to salary;
alter table AIRPORT_DETAILS rename column a_num to adhar_num;
alter table AIRPORT_DETAILS rename column seat_num to s_num;
alter table AIRPORT_DETAILS rename column s_num to seat_num;
alter table AIRPORT_DETAILS rename column adhar_num to a_num;
alter table AIRPORT_DETAILS rename column location to a_loc;
alter table EMPLOYEE_DETAILS modify column salary int;
alter table EMPLOYEE_DETAILS modify column aadhar_num int;
alter table EMPLOYEE_DETAILS modify column emp_num int ;
alter table EMPLOYEE_DETAILS modify column mob_num int;
alter table EMPLOYEE_DETAILS modify column mob_num bigint;
alter table AIRPORT_DETAILS modify column id_num int;
alter table AIRPORT_DETAILS modify column seat_num int;
alter table AIRPORT_DETAILS modify column a_num int;
alter table AIRPORT_DETAILS modify column a_loc bigint;
alter table AIRPORT_DETAILS modify column s_num bigint;